### ISSUE TITLE
Unable to transfer my sats

### ISSUE THREAD

**Issue by Imobe** [joinmarket-webui/joinmarket-webui#204]
I use the JAM app on my umbrel node. I have tried to move funds (sats) out of the JAM wallet without success. The transaction never completes when I use the enhanced privacy option. When I try to withdraw without privacy, the transaction fails.
I want to get my sats out of the JAM wallet, help me out.
Thanks.

**Comment by MaxHillebrand** [comment]
Is the deposit transaction confirmed?

(but I think you should be able to spend unconfirmed in a regular transaction, not exactly sure if you can as a taker though...)

**Comment by theborakompanioni** [comment]
> When I try to withdraw without privacy, the transaction fails. I want to get my sats out of the JAM wallet, help me out. Thanks.

I am just guessing, but this might be because you cannot practically empty a wallet with a normal send. `v0.0.5` just included the "Sweep" functionality, which can transfer all funds from a wallet. We hope to include all basic features step by step and can reach `v1.0.0` with all essential features soon.

In the meantime, as you have written down a seed phrase consisting of 12 words, please know that you will always have access to your sats and nothing gets "stuck" in Jam.

**Comment by Richie-BTC-Rich** [comment]
Just adding some info to the original poster, you can import your wallet into Sparrow and send them out from there. If you happen to have funds in multiple accounts (levels or whatever the terms is for them) Sparrow will list them on the right side as accounts after importing the seed phrase

**Comment by Imobe** [comment]
Thanks, will try that.

Sent from Yahoo Mail on Android 
 
  On Tue, 5 Apr 2022 at 0:39, ***@***.***> wrote:   


Just adding some info to the original poster, you can import your wallet into Sparrow and send them out from there. If you happen to have funds in multiple accounts (levels or whatever the terms is for them) Sparrow will list them on the right side as accounts after importing the seed phrase
