### ISSUE TITLE
Don't allow scheduled transactions when there are no spendable UTXOs

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#244]
See https://github.com/joinmarket-webui/joinmarket-webui/pull/242.

This can lead to weird states in the backend so we'll simply make sure that users don't start a transaction schedule without having something to transact with.

This should be a s simple as going over all accounts and check if there are any non-locked UTXOs.

**Comment by dnlggr** [comment]
Also check if there are at least `N` UTXOs. It's recommended to have at at least [three UTXOs ](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/SOURCING-COMMITMENTS.md) older than 5 blocks.

**Comment by dergigi** [comment]
Possibly [relevant comment](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1252#issuecomment-1115004323) from @AdamISZ:

> Three [UTXOs], because that way there is basically zero chance of a PoDLE commit finding failing even once. You could get away with paying only one [UTXO] in, if your test is set up such that a transaction will never fail

**Comment by dnlggr** [comment]
> Is something like this applicable?
> 
> ```
> const filterUtxosEligibleForScheduler = (utxos) => {
>   return utxos
>   .filter((it) => !it.frozen)
>   .filter((it) => !it.locktime)
>   .filter((it) => it.confirmations >= MIN_UTXO_CONFIRMATIONS)
>   .filter((it) => it.tries_remaining > 0)
> }
> ```

If I understand it correctly, this has to be true all UTXOs (except the frozen onces) since all UTXOs will be involved in the schedule (every mixdepth will get swept at some point).

**Comment by AdamISZ** [comment]
> This is definitely something that we'll have tho think about conceptually in the mid-term.

Yep. Notice how this kind of requirement comes as a near-direct consequence of the decentralization of the system. We originally didn't have this limitation for takers but it resulted in endless requests from anonymous takers who were really snooping to find out maker utxos.

Obviously *near*-direct - it's not like it's impossible to address this problem via other means. Fidelity bonds could work, but that's more hassle still, for the casual user. This one does not lock money nor require special addresses, nor *during most normal operation* does the user ever have to see it. So it's not like we chose this *without reference to user convenience* - it seemed like the best possible tradeoff, albeit I remember viscerally wincing when adding some of that code and documentation because I hated how much more it was requiring of the users who are paying for the service.

It may be worth further research, liquidity ads in c-ln investigated the PoDLE mechanism but haven't implemented it, but I forget exactly what they *have* implemented. There is also stuff like MPC but I fear that is going to require way too much computation/bandwidth for ad-hoc counterparty selection.

So back to practicalities:

> Is something like this applicable?

IIUC you're trying to do an early filter to make sure that the wallet has utxos necessary for the next transaction in the schedule to work? So the thing is you don't need *all* utxos to have the condition of 'tries remaining AND confs >= min'; you only need 1.

> The way I read it is that if one UTXO has no more tries remaining, it will never find a maker so the schedule can never finish?

Not exactly. In a way it's the starting condition that is most sensitive. Consider: say you have 2 utxos at the start and the schedule starts with a sweep (this is the new algo from @chris-belcher which slightly changes the dynamics of this). As long as it doesn't take 6 tries to do that sweep, you'll be OK. But the thing is the output of that sweep is in mixdepth 1 (say) and now it's the *only* utxo in that mixdepth (usually). So in the next transaction (fraction of coins to mixdepth 2 from mixdepth 1) you really only get 3 tries. You are creating a new utxo (the change) that will be the only 1 in that mixdepth 1. If your pause time is very low, initial attempts to use the commitment will fail (*in software* - you won't accidentally send it out to makers) because it's too young. But it just retries every 20 minutes or so. Then you'll send out a couple more transactions which are *not* sweep, perhaps 2 or 3 times, each time in the same situation.
Then in mixdepth 2 you might have 3 utxos now, and so it's already again, like at the start, the case that you have a lot of tries.
Another thing to bear in mind - failures due to unresponsive makers, in that 'tumbler' (or whatever) session result in that maker being kind of 'banned' from future attempts. Additionally, when failure for whatever reason occurs, the tumbler schedule generator tweaks the schedule to make it a bit more likely to succeed on the next try.

Probably you get the general idea? So the statement "if one UTXO has no more tries remaining, it will never find a maker so the schedule can never finish?" wouldn't be true if there is more than 1 utxo in the mixdepth, since you can source the PoDLE commitment from *any* utxo in the mixdepth (but not in other mixdepths - we changed that some time ago because it's really quite crappy for privacy to use a utxo from a different mixdepth, revealing a link to your maker counterparties). However it is true that this is the full failure case - if there are no utxos with any tries left, the process has to stop until and unless we change something - see 'add-utxo' below paragraph, or funding

You might wonder 'is there any way we can get more commitments' and there is, but I'm loth to ever suggest it - you can use `add-utxo.py` to add "external commitments", but you need the private key of the other utxos (from another wallet, Joinmarket or otherwise, but BIP84 only iirc) and currently it's CLI only. I think it's best left as a "pro" only feature since messing with private keys is just bad (debatable); you can't use external signing software because this is a special custom signature type.

**Comment by dnlggr** [comment]
Thanks for the insights @AdamISZ. Really helpful as always!

> Consider: say you have 2 utxos at the start and the schedule starts with a sweep (this is the new algo from chris-belcher which slightly changes the dynamics of this). As long as it doesn't take 6 tries to do that sweep, you'll be OK. But the thing is the output of that sweep is in mixdepth 1 (say) and now it's the only utxo in that mixdepth (usually). So in the next transaction (fraction of coins to mixdepth 2 from mixdepth 1) you really only get 3 tries.

Would it be correct to say that with this new scheduler/tumbler algorithm, there will likely always be a case (during a scheduler/tumbler run) where there's a mixdepth with only one UTXO (since there will be sweeps like in your example)? In other words, do we just have to live with the fact that there will be transactions for which the taker only has three tries--even if we make sure the schedule is started with three UTXOs in the initial mixdepth?

My thinking is that if we know that there'll likely be such a case in the middle of the schedule where there's only one UTXO in a mixdepth (and therefore only three tries to do the next transaction), then we could maybe also accept starting off the schedule with just a single UTXO (and three tries for the initial transaction). Or is there a difference between the initial transaction of a schedule and an intermediate transaction? I feel like I might be missing something here.
