### ISSUE TITLE
405 Method Not Allowed error while unlocking wallet

### ISSUE THREAD

**Issue by andrasfuchs** [joinmarket-webui/joinmarket-webui#387]
I use Jam v0.0.8 on Umbrel.

I created my first wallet, and named it `Jam #1`. The creation seemed to be successful, but I can't unlock the wallet.
![image](https://user-images.githubusercontent.com/910321/178136892-e56af4b8-07b7-4132-9656-741d124ca2e5.png)

When I enter the password I get the Method Not Allowed error.
![image](https://user-images.githubusercontent.com/910321/178136902-9b64365f-e1ba-4d27-bde5-5fc509f8ad4d.png)

Jam tries to call the `http://umbrel.local:5002/api/v1/wallet/Jam%20` POST method, and gets back the 405.

After this I'm not even allowed to create a new wallet (without the `#` character that probably causes the problem), because:
![image](https://user-images.githubusercontent.com/910321/178136970-c078f7e2-611a-402f-8464-3d76e371ddcc.png)

If I go back at this point, I'm stuck: I can't make the `Jam #1` inactive or delete it, and I can't create a new wallet.

**Comment by theborakompanioni** [comment]
Hey @andrasfuchs. Thanks for reporting. This has been reproduced and is fixed in https://github.com/joinmarket-webui/joinmarket-webui/pull/389 (shipped with v0.0.9 eventually).

As a temporary workaround, you have to ssh into your container and delete your wallet file in `/root/.joinmarket/wallets`. This should enable creating a new wallet. If you still have any problems or questions, feel free to write again here or in the [Telegram group](https://t.me/JoinMarketWebUI). Let me know if it worked for you.

Thank you :orange_heart:

**Comment by andrasfuchs** [comment]
Excellent! Thank you for the quick reply and fix! 👍 

It worked!
